version: '3.9'

services:
  db:
    image: mysql:8.4.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "America/Bogota"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: mysqld --default-time-zone="-05:00" # Add MySQL specific timezone

  api:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      - TZ="America/Bogota"  # Added TZ environment variable
    env_file:
      - .env
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "America/Bogota"  # Added TZ environment variable
    depends_on:
      - db

volumes:
  db_data:
